openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - Sort
  description: Adds Parameter to control sorting of returns results.
  version: 1.0.0-beta.1
paths: {}
components:
  parameters:
    sortby:
      name: sortby
      x-stac-api-fragment: sort
      in: query
      description: |-
        **Optional Extension:** Sort

        An array of property names, prefixed by either "+" for ascending or
        "-" for descending. If no prefix is provided, "+" is assumed.
      required: false
      schema:
        type: string
        example: '+id,-properties.eo:cloud_cover'
      style: form
      explode: false
  schemas:
    searchBody:
      type: object
      x-stac-api-fragment: sort
      description: |-
        **Optional Extension:** Sort
        
        Sort the results.
      properties:
        sortby:
          $ref: '#/components/schemas/sortby'
    sortby:
      type: array
      description: |
        An array of objects containing a property name and sort direction.
      minItems: 1
      items:
        type: object
        required:
          - field
          - direction
        properties:
          field:
            type: string
          direction:
            type: string
            default: asc
            enum:
              - asc
              - desc
      example:
        - field: properties.eo:cloud_cover
          direction: asc
        - field: id
          direction: desc
