openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - Query
  description: Adds parameter to compare properties and only return the items that match
  version: 1.0.0-beta.1
paths: {}
components:
  parameters:
    query:
      name: query
      x-stac-api-fragment: query
      in: query
      description: |-
        **Optional Extension:** Query
      
        Query for properties in items.
        Use the JSON form of the query used in POST.
      required: false
      schema:
        type: string
  schemas:
    searchBody:
      type: object
      x-stac-api-fragment: query
      description: |-
        **Optional Extension:** Query
      
        Allows users to query properties for specific values
      properties:
        query:
          $ref: '#/components/schemas/query'
    query:
      type: object
      description: Define which properties to query and the operations to apply
      additionalProperties:
        $ref: '#/components/schemas/queryProp'
      example:
        eo:cloud_cover:
          gt: 8
          lt: 50
        platform:
          eq: 'landsat-8'
        datetime:
          gte: '2018-02-12T00:00:00Z'
          lte: '2018-03-18T12:31:12Z'
        pl:item_type:
          startsWith: PSScene
        product:
          in:
            - foo
            - bar
            - baz
        eo:gsd:
          in:
            - 10
            - 20
    queryProp:
      description: Apply query operations to a specific property
      anyOf:
        - description: if the object doesn't contain any of the operators, it is equivalent to using the equals operator
        - type: object
          description: Match using an operator
          properties:
            eq:
              description: Find items with a property that is equal to the specified value. For strings, a case-insensitive comparison must be performed.
              nullable: true
              oneOf:
                - type: string
                - type: number
                - type: boolean
            neq:
              description: Find items that *don't* contain the specified value. For strings, a case-insensitive comparison must be performed.
              nullable: true
              oneOf:
                - type: string
                - type: number
                - type: boolean
            gt:
              description: Find items with a property value greater than the specified value.
              oneOf:
                - type: string
                  format: date-time
                - type: number
            lt:
              description: Find items with a property value less than the specified value.
              oneOf:
                - type: string
                  format: date-time
                - type: number
            gte:
              description: Find items with a property value greater than or equal the specified value.
              oneOf:
                - type: string
                  format: date-time
                - type: number
            lte:
              description: Find items with a property value less than or equal the specified value.
              oneOf:
                - type: string
                  format: date-time
                - type: number
            startsWith:
              description: Find items with a property that begins with the specified string. A case-insensitive comparison must be performed.
              type: string
            endsWith:
              description: Find items with a property that ends with the specified string. A case-insensitive comparison must be performed.
              type: string
            contains:
              description: Find items with a property that contains the specified literal string, e.g., matches ".*<STRING>.*". A case-insensitive comparison must be performed.
              type: string
            in:
              description: Find items with a property that equals at least one entry in the specified array. A case-insensitive comparison must be performed.
              type: array
              items:
                oneOf:
                  - type: string
                  - type: number