version: 2.1

references:
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v0-repo-{{ .Branch }}-{{ .Revision }}
        - v0-repo-{{ .Branch }}
        - v0-repo

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys: 
        - v0-dependencies-{{ checksum "package.json"}}
        - v0-dependencies

  restore_build: &restore_build
    restore_cache:
      keys: 
        - v0-build-{{ .Branch }}-{{ .Revision }}


jobs:
  validate:
    working_directory: ~/stac
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: init_submodules
          command: git submodule update --init --recursive
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/stac
      - run:
          name: install
          command: npm install
      - save_cache:
          key: v0-dependencies-{{ checksum "package.json"}}
          paths:
            - ~/stac/node_modules
      - run:
          name: validate
          command: npm run check
  build:
    working_directory: ~/stac
    docker:
      - image: circleci/node:12
    steps:
      - *restore_repo
      - *restore_dependencies
      - run:
          name: build openapi
          command: npm run build-openapi
      - save_cache:
          key: v0-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/stac/build
  publish:
    working_directory: ~/stac
    docker:
      - image: circleci/node:12
    steps:
      - *restore_repo
      - *restore_dependencies
      - *restore_build
      - add_ssh_keys
      - run:
          name: publish
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            npm run publish-openapi -- $CIRCLE_TAG

workflows:
  version: 2
  ci:
    jobs:
      - validate:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - validate
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              # Only dev branch, not PRs
              only: dev