openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - Core
  version: 1.0.0-beta.1
  description: >-
    This is an OpenAPI definition of the core SpatioTemporal Asset Catalog API
    specification. Any service that implements this endpoint to allow discovery of
    spatiotemporal assets can be considered a STAC API.
  contact:
    name: STAC Specification
    url: 'http://stacspec.org'
  license:
    name: Apache License 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
tags:
  - name: Core
    description: essential characteristics of a STAC API
paths:
  '/':
    get:
      tags:
        - Core
      summary: landing page
      description: |-
        Returns the root STAC Catalog or STAC Collection that is the entry point
        for users to browse with STAC Browser or for search engines to crawl.
        This can either return a single STAC Collection or more commonly a STAC
        catalog.

        The landing page provides links to the
        API definition (link relations `service-desc` and `service-doc`)
        and the STAC records such as collections/catalogs (link relation `child`)
        or items (link relation `item`).

        Extensions may add additional links with new relation types.
      operationId: getLandingPage
      responses:
        '200':
          $ref: '#/components/responses/LandingPage'
        '500':
          $ref: 'commons.yaml#/components/responses/Error'
components:
  schemas:
    landingPage:
      allOf:
        - $ref: 'commons.yaml#/components/schemas/catalog'
        - $ref: 'commons.yaml#/components/schemas/conformanceClasses'
  responses:
    LandingPage:
      description: |-
        The landing page provides links to the API definition
        (link relations `service-desc` and `service-doc`)
        and the Feature Collections (path `/collections`, link relation
        `data`).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/landingPage'
          example:
            stac_version: 1.0.0-beta.1
            id: sentinel
            title: Copernicus Sentinel Imagery
            description: Catalog of Copernicus Sentinel 1 and 2 imagery.
            conformsTo:
              - 'https://api.stacspec.org/v1.0.0-beta.1/core'
            links:
              - href: 'http://data.example.org/'
                rel: self
                type: application/json
                title: this document
              - href: 'http://data.example.org/api'
                rel: service-desc
                type: application/vnd.oai.openapi+json;version=3.0
                title: the API definition
              - href: 'http://data.example.org/api.html'
                rel: service-doc
                type: text/html
                title: the API documentation
              - href: 'http://data.example.org/sentinel-1'
                rel: child
                type: application/json
                title: Sentinel 1 Catalog
              - href: 'http://data.example.org/sentinel-2'
                rel: child
                type: application/json
                title: Sentinel 2 Catalog